name: Hello Action

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: 인사 출력
        run: echo "Hello! Action이 실행됐어요!"

      - name: 현재 시간 출력
        run: date

      - name: push한 파일 목록 출력
        run: git log --name-only -1
